const C=["C1","C2","C3","C4","C5","C6","C7","C8","C9","C10"], palette=["#58d6ff","#ff647c","#ffb454","#72e0a5","#bd8cff","#67a8ff","#ff77b7","#ff8d5c","#6ee7d0","#aab4c8"];let data,selected="ALL",metric="share";
const $=s=>document.querySelector(s),fmt=(x,d=1)=>Number(x).toFixed(d);
function duration(e){return Math.max(0,e.end-e.start)}
function metrics(){const T=data.work.duration_seconds;return Object.fromEntries(C.map(c=>{const es=data.events.filter(e=>e.class===c&&e.status==="present"),t=es.reduce((a,e)=>a+duration(e),0),n=es.length;return[c,{N:n,T:t,share:t/T,density:n/(T/60),coverage:data.coverage.temporal,repeatability:n?new Set(es.map(e=>Math.floor(e.start/600))).size/n:0}]}))}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
function drawBars(m){const W=760,H=300,p=45,max=Math.max(...C.map(c=>m[c][metric==="share"?"share":"N"]),.001),bar=(W-70)/10-8;let svg='<svg viewBox="0 0 760 300" class="chart" role="img">';C.forEach((c,i)=>{const v=m[c][metric==="share"?"share":"N"],h=(H-70)*v/max,x=p+i* ((W-70)/10),y=H-35-h;svg+=`<rect x="${x}" y="${y}" width="${bar}" height="${h}" rx="5" fill="${palette[i]}" opacity="${selected==="ALL"||selected===c?1:.25}"/><text x="${x+bar/2}" y="${H-15}" fill="#9aa7ba" font-size="12" text-anchor="middle">${c}</text><text x="${x+bar/2}" y="${Math.max(18,y-5)}" fill="#e9eef8" font-size="11" text-anchor="middle">${metric==="share"?fmt(v*100)+"%":v}</text>`});return svg+"</svg>"}
function drawTimeline(){const W=760,H=340,p=42,T=data.work.duration_seconds,lane=25;let svg='<svg viewBox="0 0 760 340" class="chart">';data.events.forEach((e,i)=>{if(selected!=="ALL"&&e.class!==selected)return;const y=15+(i%12)*lane,x=p+(e.start/T)*(W-p-20),w=Math.max(3,(duration(e)/T)*(W-p-20));svg+=`<rect x="${x}" y="${y}" width="${w}" height="16" rx="4" fill="${palette[C.indexOf(e.class)]}"/><text x="${x+3}" y="${y+12}" font-size="9" fill="#061018">${esc(e.id)} · ${e.class}</text>`});for(let k=0;k<=6;k++){const x=p+k*(W-p-20)/6;svg+=`<line x1="${x}" y1="0" x2="${x}" y2="325" stroke="#263247"/><text x="${x}" y="338" fill="#8e9aad" font-size="10" text-anchor="middle">${Math.round(T*k/6/60)}m</text>`}return svg+"</svg>"}
function drawDensity(){const bins=12,T=data.work.duration_seconds,b=T/bins,W=760,H=280,p=45,max=1;const counts=Array(bins).fill(0);data.events.forEach(e=>{if(selected==="ALL"||e.class===selected)counts[Math.min(bins-1,Math.floor(e.start/b))]++});const mx=Math.max(...counts,1),bw=(W-p-20)/bins-5;let svg='<svg viewBox="0 0 760 280" class="chart">';counts.forEach((n,i)=>{const h=190*n/mx,x=p+i*(bw+5),y=220-h;svg+=`<rect x="${x}" y="${y}" width="${bw}" height="${h}" rx="4" fill="#78e6b2"/><text x="${x+bw/2}" y="${y-5}" fill="#e9eef8" font-size="11" text-anchor="middle">${fmt(n/(b/60),2)}</text>`});return svg+"</svg>"}
function drawWheel(m){const cx=180,cy=180,R=150,r=42,max=Math.max(...C.map(c=>m[c].share),.0001);let svg='<svg viewBox="0 0 360 360" class="chart">';C.forEach((c,i)=>{const a0=(i*36-90)*Math.PI/180,a1=((i+1)*36-90)*Math.PI/180,rr=42+(m[c].share/max)*108,x1=cx+rr*Math.cos(a0),y1=cy+rr*Math.sin(a0),x2=cx+rr*Math.cos(a1),y2=cy+rr*Math.sin(a1),ix1=cx+r*Math.cos(a0),iy1=cy+r*Math.sin(a0),ix2=cx+r*Math.cos(a1),iy2=cy+r*Math.sin(a1);svg+=`<path d="M${ix1} ${iy1} L${x1} ${y1} A${rr} ${rr} 0 0 1 ${x2} ${y2} L${ix2} ${iy2} A${r} ${r} 0 0 0 ${ix1} ${iy1}Z" fill="${palette[i]}" opacity="${selected==="ALL"||selected===c?0.9:.18}"/><text x="${cx+(rr+12)*Math.cos((a0+a1)/2)}" y="${cy+(rr+12)*Math.sin((a0+a1)/2)}" fill="#e9eef8" font-size="10" text-anchor="middle">${c}</text>`}return svg+`<circle cx="${cx}" cy="${cy}" r="${r-2}" fill="#080b12"/><text x="${cx}" y="${cy-5}" fill="#e9eef8" font-size="12" text-anchor="middle">screen_time</text><text x="${cx}" y="${cy+13}" fill="#8e9aad" font-size="10" text-anchor="middle">share</text></svg>`}
function render(){const m=metrics();$("#metrics").innerHTML=C.map(c=>`<div class="card"><div class="muted">${c} · ${data.ontology.classes[c]}</div><div class="metric">${fmt(m[c].share*100)}%</div><div class="small">T=${m[c].T}s · N=${m[c].N} · ρ=${fmt(m[c].density,2)}/мин</div></div>`).join("");$("#bars").innerHTML=drawBars(m);$("#timeline").innerHTML=drawTimeline();$("#density").innerHTML=drawDensity();$("#wheel").innerHTML=drawWheel(m);$("#selected").textContent=selected==="ALL"?"Все категории":selected+" — "+data.ontology.classes[selected];$("#passport").innerHTML=`<table class="table"><tr><th>Параметр</th><th>Значение</th></tr><tr><td>Runtime</td><td>${Math.floor(data.work.duration_seconds/60)} мин ${data.work.duration_seconds%60} с</td></tr><tr><td>События</td><td>${data.events.length}</td></tr><tr><td>Temporal coverage</td><td>${fmt(data.coverage.temporal*100)}%</td></tr><tr><td>Modalities</td><td>vision ${fmt(data.coverage.modalities.vision*100)}%, audio ${fmt(data.coverage.modalities.audio*100)}%, text ${fmt(data.coverage.modalities.text*100)}%</td></tr><tr><td>Validation</td><td>illustrative only</td></tr></table>`;}
function controls(){const el=$("#controls");el.innerHTML='<button class="active" data-c="ALL">Все</button>'+C.map(c=>`<button data-c="${c}">${c}</button>`).join("");el.onclick=e=>{const b=e.target.closest("button");if(!b)return;selected=b.dataset.c;el.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()}}
fetch("data/demo_content.json").then(r=>r.json()).then(x=>{data=x;controls();render()}).catch(e=>{$("#app").innerHTML='<div class="notice">Не удалось загрузить demo_content.json. Откройте проект через GitHub Pages или локальный HTTP-сервер.</div>'});
